### ISSUE TITLE
Tooltips en barchart

### ISSUE THREAD

**Issue by ch3k0** [mxabierto/dataviz#7]
Algunos tooltips en la gráfica de barras se muestran en una posición inadecuada respecto al elemento seleccionado, esto solo pasa cuando se usa un json con valores negativos.

**Comment by ch3k0** [comment]
http://i.imgur.com/SniS0Gi.png

**Comment by esaugtz** [comment]
Se corrige la forma en que se crea el tooltip para los números negativos.

http://imgur.com/oBim9P6
