### ISSUE TITLE
Nombres en los ejes del barchart

### ISSUE THREAD

**Issue by ch3k0** [mxabierto/dataviz#8]
Con la nueva versión del barchart no se están mostrando el nombre de los ejes

**Comment by esaugtz** [comment]
Esta corregido, los nombres para los ejes se puedes setear en el json y se mostrarán en la gráfica.

{
  "ejex": "Transporte",
  "ejey": "Personas",
  "valores": [
    {
      "key": "Chihuahua",
      "values": [
        {"x": "Coche", "y": 35650},
        {"x": "Coche compartido", "y": 18546},
        {"x": "Metro", "y": 12654},
        {"x": "Bicicleta", "y": 12654},
        {"x": "A pie", "y": 12654},
        {"x": "Motocicleta", "y": 12654},
        {"x": "Taxi", "y": 12654}
      ]
    }
  ]
}
