### ISSUE TITLE
Piechart

### ISSUE THREAD

**Issue by ch3k0** [mxabierto/dataviz#9]
Se debería mejorar la gráfica de pie chart ya se considera muy simple, se podría mejorar la parte de los "labels" donde indique con texto a que pertenece cada sección.

**Comment by esaugtz** [comment]
Agregamos una nueva versión para esta gráfica, con mejoras en los datos a mostrar en tooltip y totalmente responsiva.
La nueva versión la podrán encontrar en el siguiente repositorio:
https://github.com/opintel/PieChart/tree/responsive
